# Generated by Django 2.1.15 on 2020-07-13 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('user_name', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Consumption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_id', models.CharField(blank=True, max_length=100, null=True)),
                ('nfc_tag', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.CharField(blank=True, max_length=100, null=True)),
                ('consumption', models.CharField(blank=True, max_length=100, null=True)),
                ('unit', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConsumptionMobile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_id', models.CharField(blank=True, max_length=100, null=True)),
                ('last_reading_date', models.DateTimeField(blank=True, null=True)),
                ('new_reading_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DegreeDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_degree', models.CharField(blank=True, max_length=100, null=True)),
                ('period_form', models.CharField(blank=True, max_length=100, null=True)),
                ('period_to', models.CharField(blank=True, max_length=100, null=True)),
                ('month', models.CharField(blank=True, max_length=100, null=True)),
                ('degree_days', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MetaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_id', models.CharField(blank=True, max_length=100, null=True)),
                ('nfc_tag', models.CharField(blank=True, max_length=100, null=True)),
                ('media_type', models.CharField(blank=True, max_length=100, null=True)),
                ('energy_media_type', models.CharField(blank=True, max_length=100, null=True)),
                ('meter_point_description', models.CharField(blank=True, max_length=100, null=True)),
                ('energy_unit', models.CharField(blank=True, max_length=100, null=True)),
                ('group', models.CharField(blank=True, max_length=100, null=True)),
                ('column_line', models.CharField(blank=True, max_length=100, null=True)),
                ('meter_location', models.CharField(blank=True, max_length=100, null=True)),
                ('energy_art', models.CharField(blank=True, max_length=100, null=True)),
                ('supply_area_child', models.CharField(blank=True, max_length=100, null=True)),
                ('meter_level_structure', models.CharField(blank=True, max_length=100, null=True)),
                ('supply_area_parent', models.CharField(blank=True, max_length=100, null=True)),
                ('meta_data_picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('longtitude', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShopData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nfc_uid', models.CharField(blank=True, max_length=100, null=True)),
                ('nfc_store_id', models.CharField(blank=True, max_length=100, null=True)),
                ('store_name', models.CharField(blank=True, max_length=100, null=True)),
                ('store_address', models.CharField(blank=True, max_length=100, null=True)),
                ('store_postcode', models.CharField(blank=True, max_length=100, null=True)),
                ('stroe_city', models.CharField(blank=True, max_length=100, null=True)),
                ('store_picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('longtitude', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='VoteData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_email', models.CharField(blank=True, max_length=100, null=True)),
                ('vote_name', models.CharField(blank=True, max_length=100, null=True)),
                ('vote', models.CharField(blank=True, max_length=100, null=True)),
                ('nfc_store_id', models.CharField(blank=True, max_length=100, null=True)),
                ('election', models.CharField(blank=True, max_length=100, null=True)),
                ('shop_name', models.CharField(blank=True, max_length=100, null=True)),
                ('longtitude', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
