# Generated by Django 2.1.15 on 2020-09-20 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumptionMobile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_id', models.CharField(blank=True, max_length=100, null=True)),
                ('new_value', models.CharField(blank=True, max_length=100, null=True)),
                ('reading_date', models.DateTimeField(blank=True, null=True)),
                ('read_by', models.CharField(blank=True, max_length=100, null=True)),
                ('remark', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DegreeDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_degree', models.CharField(blank=True, max_length=100, null=True)),
                ('period_form', models.DateTimeField(blank=True, null=True)),
                ('period_to', models.DateTimeField(blank=True, null=True)),
                ('month', models.CharField(blank=True, max_length=100, null=True)),
                ('degree_days', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MetaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technical_category', models.CharField(blank=True, max_length=100, null=True)),
                ('equipment_name', models.CharField(blank=True, max_length=100, null=True)),
                ('nfc_tag', models.CharField(blank=True, max_length=100, null=True)),
                ('service_interval', models.CharField(blank=True, max_length=100, null=True)),
                ('legit', models.CharField(blank=True, max_length=100, null=True)),
                ('latest_service', models.CharField(blank=True, max_length=100, null=True)),
                ('contacts', models.CharField(blank=True, max_length=100, null=True)),
                ('longititude', models.CharField(blank=True, max_length=100, null=True)),
                ('lattitude', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Remark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('user_name', models.CharField(max_length=30)),
                ('company', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('user_authority', models.CharField(max_length=100)),
                ('active', models.CharField(max_length=100)),
                ('technical_authority', models.CharField(max_length=100)),
                ('reset_time', models.DateTimeField(blank=True, null=True)),
                ('reset_id', models.CharField(max_length=100)),
            ],
        ),
    ]
