# Generated by Django 2.1.15 on 2020-07-07 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_app_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_id', models.CharField(blank=True, max_length=100, null=True)),
                ('nfc_tag', models.CharField(blank=True, max_length=100, null=True)),
                ('media_type', models.CharField(blank=True, max_length=100, null=True)),
                ('energy_media_type', models.CharField(blank=True, max_length=100, null=True)),
                ('meter_point_description', models.CharField(blank=True, max_length=100, null=True)),
                ('energy_unit', models.CharField(blank=True, max_length=100, null=True)),
                ('group', models.CharField(blank=True, max_length=100, null=True)),
                ('column_line', models.CharField(blank=True, max_length=100, null=True)),
                ('meter_location', models.CharField(blank=True, max_length=100, null=True)),
                ('energy_art', models.CharField(blank=True, max_length=100, null=True)),
                ('supply_area_child', models.CharField(blank=True, max_length=100, null=True)),
                ('meter_level_structure', models.CharField(blank=True, max_length=100, null=True)),
                ('supply_area_parent', models.CharField(blank=True, max_length=100, null=True)),
                ('meta_data_picture', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
