# Generated by Django 2.1.15 on 2020-07-08 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_app_api', '0002_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='DegreeDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_degree', models.CharField(blank=True, max_length=100, null=True)),
                ('period_form', models.CharField(blank=True, max_length=100, null=True)),
                ('period_to', models.CharField(blank=True, max_length=100, null=True)),
                ('month', models.CharField(blank=True, max_length=100, null=True)),
                ('degree_days', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
