# Generated by Django 2.1.15 on 2020-09-27 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_app_api', '0002_technicalcatergory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metadata',
            old_name='contacts',
            new_name='column_line',
        ),
        migrations.RenameField(
            model_name='metadata',
            old_name='equipment_name',
            new_name='energy_art',
        ),
        migrations.RenameField(
            model_name='metadata',
            old_name='latest_service',
            new_name='energy_media_type',
        ),
        migrations.RenameField(
            model_name='metadata',
            old_name='lattitude',
            new_name='energy_unit',
        ),
        migrations.RenameField(
            model_name='metadata',
            old_name='legit',
            new_name='fabricate',
        ),
        migrations.RenameField(
            model_name='metadata',
            old_name='longititude',
            new_name='fabricationDate',
        ),
        migrations.RenameField(
            model_name='metadata',
            old_name='service_interval',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='metadata',
            old_name='technical_category',
            new_name='impUnit',
        ),
        migrations.AddField(
            model_name='metadata',
            name='latitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='metadata',
            name='longtitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='metadata',
            name='media_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='metadata',
            name='meta_data_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='metadata',
            name='meter_level_structure',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='metadata',
            name='meter_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='metadata',
            name='meter_point_description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='metadata',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='metadata',
            name='screenCharacters',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='metadata',
            name='serialNumber',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='metadata',
            name='supply_area_child',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='metadata',
            name='supply_area_parent',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='metadata',
            name='tag_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
