# Generated by Django 2.1.15 on 2020-09-27 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_app_api', '0005_auto_20200927_0944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metadata_main',
            old_name='lattitude',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='metadata_main',
            old_name='longititude',
            new_name='longitude',
        ),
    ]
