# Generated by Django 2.1.15 on 2020-09-28 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_app_api', '0006_auto_20200927_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaData_Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_name', models.CharField(blank=True, max_length=100, null=True)),
                ('service_repair', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('due_time', models.CharField(blank=True, max_length=100, null=True)),
                ('serviced_by', models.CharField(blank=True, max_length=100, null=True)),
                ('comment', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
